name: On-Pr Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  Mocking-Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  Linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

  Build-Test:
    runs-on: ubuntu-latest

    needs: [Mocking-Tests, Linting]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Build Docker Image (Test Build)
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: false
    
